image: python:latest

cache:
  paths:
    - .venv/

before_script:
  - python --version  # For debugging
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv
  - poetry shell

test:
  script:
    - pytest

  tags:
    - docker
    - dihi

# deploy:
#   script:
#     - poetry build
#     - poetry config repositories.gitlab "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi"
#     - poetry config http-basic.gitlab gitlab-ci-token "$CI_JOB_TOKEN"
#     - poetry publish --repository gitlab
#   tags:
#     - docker
#     - dihi
