image: python:latest

cache:
  paths:
    - .venv/

before_script:
  - python --version  # For debugging
  - pip install poetry
  - poetry --version
  - poetry config virtualenvs.in-project true
  - poetry install -vv

test:
  script:
    - pytest

  tags:
    - docker
    - dihi
